# Site
title: esmyy
favicon: /images/favicon.png
subtitle: ""
description: ""
keywords: "esmyy, myy, 马月月, 月月, 月月的个人网站"
author: Esmyy
language: zh-CN
timezone: ""

## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://mayueyue.com
permalink: :year/:month/:day/:title.html
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# First Screen
firstScreen:
  image: /images/the-great-wall.jpeg
  date: "2022年11月4日"
  addr: "北京朝阳区"
  description: "爱我所爱，长久不懈"

# Home Page
recentPicture:
  one:
    image: /images/3601.jpg
    text: ""
    link: ""
  two:
    image: /images/2101.jpg
    text: ""
    link: ""
  three:
    image: /images/3602.jpg
    text: ""
    link: ""
  four:
    image: /images/2102.jpg
    text: ""
    link: ""

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: 2
  wrap: true
  hljs: true
  engine: highlight

prism_plugin:
  mode: "preprocess" # realtime/preprocess
  theme: "default"
  line_number: true # default false
  custom_css:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date
  pagination_dir: page

archive_generator:
  enabled: true
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  order_by: -date

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# 压缩
neat_enable: true
neat_html:
  enable: true
  exclude:
neat_css:
  enable: true
  exclude:
    - "*.min.css"
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - "*.min.js"
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: esmyy

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ""

sitemap:
  path:
    - sitemap.xml
    - sitemap.txt
  rel: false
  tags: true
  categories: true

# tag generator
tag_generator:
  per_page: 10
  order_by: -date

toc:
  maxdepth: 3
  class: toc
  slugify: transliteration
  decodeEntities: false
  anchor:
    position: after
    symbol: "#"
    style: header-anchor

post_wordcount:
  date: true # 发布日期
  update: true # 更新日期
  wordCount: true # 文章字数统计
  totalCount: true # 站点总文章字数
  min2read: true # 文章阅读时长
  readCount: true # 文章阅读次数

# hexo_external_link:
#   enable: false
#   enable_base64_encode: false
#   url_param_name: ""
#   html_file_name: "go.html"
#   target_blank: true
#   link_rel: "external nofollow noopener noreferrer"
#   domain: "your_domain" # 如果开启了防盗链
#   safety_chain: true

# feed:
#   type: atom
#   path: atom.xml
#   limit: 20;
#   hub:
#     content:
#       content_limit: 140
#   content_limit_delim: " "
#   order_by: -date;

# jsdelivr CDN
jsdelivr:
  enable: true
  gh_user: esmyy
  gh_repo: imagehost
  baseUrl: cdn.jsdelivr.net
