/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  title: "esmyy",
  tagline: "我亦无他，唯手熟尔",
  url: "https://esmyy.com",
  baseUrl: "/",
  onBrokenLinks: "throw",
  onBrokenMarkdownLinks: "warn",
  favicon: "img/favicon.png",
  markdown: {
    mermaid: true,
  },
  themes: ["@docusaurus/theme-mermaid"],
  customFields: {
    cover: {
      textColor: "#fff",
      img: "https://cdn.jsdelivr.net/gh/esmyy/esmyy.github.io@gh-pages/images/air-beijing-chengdu.jpg",
      description: "北京飞往成都",
      date: "2022年10月11日",
    },
  },
  organizationName: "facebook",
  projectName: "docusaurus",
  i18n: {
    defaultLocale: "zh-Hans",
    locales: ["zh-Hans"],
    path: "i18n",
    localeConfigs: {},
  },
  presets: [
    [
      "classic",
      {
        docs: {
          sidebarPath: "/Users/fengpeng/handbook/sidebars.js",
          editUrl:
            "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/",
        },
        blog: {
          showReadingTime: true,
          editUrl:
            "https://github.com/facebook/docusaurus/tree/main/packages/create-docusaurus/templates/shared/",
        },
        theme: {
          customCss: "/Users/fengpeng/handbook/src/css/custom.css",
        },
      },
    ],
  ],
  plugins: ["./postcss-tailwind-loader", "./mindmap-plugin"],
  themeConfig: {
    tableOfContents: {
      minHeadingLevel: 2,
      maxHeadingLevel: 4,
    },
    navbar: {
      logo: {
        alt: "logo",
        src: "img/favicon.png",
      },
      items: [
        {
          position: "left",
          label: "知识手册",
          to: "/docs",
        },
        {
          to: "/docs/frameworks",
          label: "前端框架",
          position: "left",
        },
        {
          to: "/docs/qa",
          label: "Q & A",
          position: "left",
        },
        {
          href: "https://github.com/esmyy",
          label: "GitHub",
          position: "right",
        },
      ],
      hideOnScroll: false,
    },
    footer: {
      style: "dark",
      links: [
        {
          title: "Docs",
          items: [
            {
              label: "Tutorial",
              to: "/docs",
            },
          ],
        },
        {
          title: "Community",
          items: [
            {
              label: "Stack Overflow",
              href: "https://stackoverflow.com/questions/tagged/docusaurus",
            },
            {
              label: "Discord",
              href: "https://discordapp.com/invite/docusaurus",
            },
            {
              label: "Twitter",
              href: "https://twitter.com/docusaurus",
            },
          ],
        },
        {
          title: "More",
          items: [
            {
              label: "Blog",
              to: "https://www.esmyy.com/blog",
            },
            {
              label: "GitHub",
              href: "https://github.com/facebook/docusaurus",
            },
          ],
        },
      ],
      copyright: "Copyright © 2023 My Project, Inc. Built with Docusaurus.",
    },
    prism: {
      theme: {
        plain: {
          color: "#f8f8f2",
          backgroundColor: "#272822",
        },
        styles: [
          {
            types: ["changed"],
            style: {
              color: "rgb(162, 191, 252)",
              fontStyle: "italic",
            },
          },
          {
            types: ["deleted"],
            style: {
              color: "#f92672",
              fontStyle: "italic",
            },
          },
          {
            types: ["inserted"],
            style: {
              color: "rgb(173, 219, 103)",
              fontStyle: "italic",
            },
          },
          {
            types: ["comment"],
            style: {
              color: "#8292a2",
              fontStyle: "italic",
            },
          },
          {
            types: ["string", "url"],
            style: {
              color: "#a6e22e",
            },
          },
          {
            types: ["variable"],
            style: {
              color: "#f8f8f2",
            },
          },
          {
            types: ["number"],
            style: {
              color: "#ae81ff",
            },
          },
          {
            types: ["builtin", "char", "constant", "function", "class-name"],
            style: {
              color: "#e6db74",
            },
          },
          {
            types: ["punctuation"],
            style: {
              color: "#f8f8f2",
            },
          },
          {
            types: ["selector", "doctype"],
            style: {
              color: "#a6e22e",
              fontStyle: "italic",
            },
          },
          {
            types: ["tag", "operator", "keyword"],
            style: {
              color: "#66d9ef",
            },
          },
          {
            types: ["boolean"],
            style: {
              color: "#ae81ff",
            },
          },
          {
            types: ["namespace"],
            style: {
              color: "rgb(178, 204, 214)",
              opacity: 0.7,
            },
          },
          {
            types: ["tag", "property"],
            style: {
              color: "#f92672",
            },
          },
          {
            types: ["attr-name"],
            style: {
              color: "#a6e22e !important",
            },
          },
          {
            types: ["doctype"],
            style: {
              color: "#8292a2",
            },
          },
          {
            types: ["rule"],
            style: {
              color: "#e6db74",
            },
          },
        ],
      },
      darkTheme: {
        plain: {
          color: "#9CDCFE",
          backgroundColor: "#1E1E1E",
        },
        styles: [
          {
            types: ["prolog"],
            style: {
              color: "rgb(0, 0, 128)",
            },
          },
          {
            types: ["comment"],
            style: {
              color: "rgb(106, 153, 85)",
            },
          },
          {
            types: [
              "builtin",
              "changed",
              "keyword",
              "interpolation-punctuation",
            ],
            style: {
              color: "rgb(86, 156, 214)",
            },
          },
          {
            types: ["number", "inserted"],
            style: {
              color: "rgb(181, 206, 168)",
            },
          },
          {
            types: ["constant"],
            style: {
              color: "rgb(100, 102, 149)",
            },
          },
          {
            types: ["attr-name", "variable"],
            style: {
              color: "rgb(156, 220, 254)",
            },
          },
          {
            types: ["deleted", "string", "attr-value", "template-punctuation"],
            style: {
              color: "rgb(206, 145, 120)",
            },
          },
          {
            types: ["selector"],
            style: {
              color: "rgb(215, 186, 125)",
            },
          },
          {
            types: ["tag"],
            style: {
              color: "rgb(78, 201, 176)",
            },
          },
          {
            types: ["tag"],
            languages: ["markup"],
            style: {
              color: "rgb(86, 156, 214)",
            },
          },
          {
            types: ["punctuation", "operator"],
            style: {
              color: "rgb(212, 212, 212)",
            },
          },
          {
            types: ["punctuation"],
            languages: ["markup"],
            style: {
              color: "#808080",
            },
          },
          {
            types: ["function"],
            style: {
              color: "rgb(220, 220, 170)",
            },
          },
          {
            types: ["class-name"],
            style: {
              color: "rgb(78, 201, 176)",
            },
          },
          {
            types: ["char"],
            style: {
              color: "rgb(209, 105, 105)",
            },
          },
        ],
      },
      additionalLanguages: [],
      magicComments: [
        {
          className: "theme-code-block-highlighted-line",
          line: "highlight-next-line",
          block: {
            start: "highlight-start",
            end: "highlight-end",
          },
        },
      ],
    },
    mermaid: {
      theme: {
        light: "forest",
        dark: "forest",
      },
      options: {
        flowchart: {
          htmlLabels: true,
          diagramPadding: 0,
        },
        themeVariables: {},
      },
    },
    colorMode: {
      defaultMode: "light",
      disableSwitch: false,
      respectPrefersColorScheme: false,
    },
    docs: {
      versionPersistence: "localStorage",
      sidebar: {
        hideable: false,
        autoCollapseCategories: false,
      },
    },
    metadata: [],
  },
  baseUrlIssueBanner: true,
  onDuplicateRoutes: "warn",
  staticDirectories: ["static"],
  scripts: [],
  headTags: [],
  stylesheets: [],
  clientModules: [],
  titleDelimiter: "|",
  noIndex: false,
};
